#!/usr/bin/env node
/**
 * Bundle src/content/*.md into src/content/generated.ts at build time.
 *
 * Cloudflare Workers have no runtime filesystem, so libs/content.ts cannot
 * fs.readFileSync the markdown at request time. This script (run via the
 * `prebuild` npm hook) reads the .md files on Node and emits a TS module of
 * string literals that gets bundled into the Worker. Keep editing the .md
 * files normally; this regenerates on every build.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const contentDir = path.join(__dirname, '..', 'src', 'content')

const pages = {}
for (const f of fs.readdirSync(contentDir)) {
  if (f.endsWith('.md')) {
    pages[f.replace(/\.md$/, '')] = fs.readFileSync(path.join(contentDir, f), 'utf-8')
  }
}

const news = []
const newsDir = path.join(contentDir, 'news')
if (fs.existsSync(newsDir)) {
  for (const f of fs.readdirSync(newsDir).filter((f) => f.endsWith('.md')).sort()) {
    news.push({ slug: f.replace(/\.md$/, ''), raw: fs.readFileSync(path.join(newsDir, f), 'utf-8') })
  }
}

const out =
  `// AUTO-GENERATED by scripts/gen-content.mjs — do not edit. Run \`npm run build\` to refresh.\n` +
  `export const pages: Record<string, string> = ${JSON.stringify(pages, null, 2)}\n\n` +
  `export const news: { slug: string; raw: string }[] = ${JSON.stringify(news, null, 2)}\n`

fs.writeFileSync(path.join(contentDir, 'generated.ts'), out)
console.log(`gen-content: ${Object.keys(pages).length} page(s), ${news.length} news item(s)`)
